FROM golang:1.26rc2-alpine

ARG git_tag
ARG git_commit

RUN apk add --no-cache git build-base

WORKDIR /go/src/github.com/justpark/auth/hydra

ENV GO111MODULE=on

ADD . .

RUN go install .
RUN go build -buildmode=plugin -o /memtest.so ./test/e2e/plugin/memtest.go

ENTRYPOINT ["hydra"]

CMD ["serve", "all"]
